#!/usr/bin/env node
// Regenerates src/tools.ts (the OFFLINE FALLBACK snapshot) from the live
// catalog. Source of truth is main_service/mcp/tools.js — either via the
// monorepo checkout next door (default) or from the live server.
//
//   node scripts/regen-tools.mjs                    # from ../tickerbot (default)
//   node scripts/regen-tools.mjs --live             # from https://api.tickerbot.io/mcp/tools
//
// Staleness in the snapshot only matters during a Tickerbot outage — online
// users always dispatch against the live catalog fetched at startup.
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '../src/tools.ts')

let tools
if (process.argv.includes('--live')) {
  const res = await fetch('https://api.tickerbot.io/mcp/tools')
  if (!res.ok) throw new Error(`GET /mcp/tools -> ${res.status}`)
  tools = (await res.json()).tools
} else {
  const require = createRequire(import.meta.url)
  tools = require(resolve(here, '../../tickerbot/main_service/mcp/tools.js')).tools
}

const HEADER = `// OFFLINE FALLBACK tool registry for the Tickerbot MCP server.
//
// GENERATED by scripts/regen-tools.mjs — do not edit by hand.
//
// The canonical tool list lives in main_service/mcp/tools.js on the
// server. At startup, this package fetches \`\${baseUrl}/mcp/tools\` and
// uses the live catalog — see src/index.ts. This file is the snapshot
// we fall back to if the fetch fails (offline, server down, network
// blip), and it's also what gets bundled at npm-publish time for
// freshness in cold-start scenarios.
//
// Staleness here is fine. Updating this file does NOT change behavior
// for online users — they always see whatever main_service is serving.
// Refresh with: node scripts/regen-tools.mjs   (or --live)

export type ParamLocation = 'path' | 'query' | 'body'

export interface ToolDef {
  name: string
  description: string
  inputSchema: {
    type: 'object'
    properties: Record<string, JsonSchemaProp>
    required?: readonly string[]
  }
  endpoint: {
    method: 'GET' | 'POST' | 'PATCH' | 'DELETE'
    /** Path template. Path params appear as \`{name}\` placeholders. */
    path: string
    /** Where each declared input param goes. */
    paramLocation: Record<string, ParamLocation>
  }
}

interface JsonSchemaProp {
  type: 'string' | 'integer' | 'number' | 'boolean' | 'array' | 'object'
  description: string
  enum?: readonly string[]
  default?: unknown
  items?: { type: string }
}

export const tools: readonly ToolDef[] = `

const FOOTER = ` as const

export function findTool(name: string): ToolDef | undefined {
  return tools.find((t) => t.name === name)
}
`

writeFileSync(out, HEADER + JSON.stringify(tools, null, 2) + FOOTER)
console.log(`wrote ${out}: ${tools.length} tools`)
